### ISSUE TITLE
Important: Review functionality for card cancellation/expiry, including possiblity to 'unexpire' a card.

### ISSUE THREAD

**Issue by johnsirett** [BuzzardMothTeam/BuzzardMoth#9]
We need to have a short discussion on what functionality should be available for card cancellation/expiry. 

Right now, cards are only first issued when registering a new competitor, users can cancel cards manually, which will result in a new card being issued right away, and various triggers such as team/competitor elimination will result in a card being expired. Card info cannot be directly edited by users.

This raises a few questions:
 * Should the user be able to 'unexpire' expired cards, by issuing a new one (probably), or by resetting the status of an existing one (probably not).
 * Should there be a way to force issuing a new card (probably not, we should try to limit )?
 * Should there be a way to cancel a card, without issuing a new one?

We also still need to prevent repeat cancellations and prevent users from cancelling expired cards, as per closed bug #8.

**Comment by AndyRockZZZ** [comment]
For the unexpired question, I would prefer that I will be best to get an 'unexpired function' that way that if you made an mistake, you can always undo the cause.

**Comment by johnsirett** [comment]
Agreed. I have now fixed bug #8 completely (repeat cancellations are now checked for).

**Comment by johnsirett** [comment]
Ok I've made a few changes and I think we can close this now.
